### ISSUE TITLE
Rifgen run error

### ISSUE THREAD

**Issue by snhoau** [rifdock/rifdock#118]
Dear authors:

Hello, I am try to run rifgen as instruction, the command is following

$RIFDOCK/build/apps/rosetta/rifgen @input/rifgen.flag > rifgen.log 2>&1
and no error massages shown, but when I see the log file, it's not working correctly.

The rifgen.log shown error as following:
FAILED ASSERTION:
reename(ala_rot_) == "ALA"

EXIT FROM:
/home/root/Downloads/rifdock/schemelib/scheme/chemical/RotamerIndex.hh line: 860

Please tall me, what should I do to avoid this mistake? thanks

**Comment by LongxingCao** [comment]
Compile rosetta/rifdock with a different gcc version. gcc6.3 works for me.
