### ISSUE TITLE
rifgen link to rosetta

### ISSUE THREAD

**Issue by ShuhaoGithub** [rifdock/rifdock#136]
I ran $RIFDOCK/build/apps/rosetta/rifgen @input/rifgen.flag > rifgen.log 2>&1 and got this log. I don't know why the program is locating my rosetta at /home/me/rifdock/rifdock_rosetta/main. I already claimed the correct rosetta path by exporting CMAKE_FINAL_ROSETTA_PATH and CMAKE_ROSETTA_PATH. What else can I do to change the address? Thanks!

core.init: Rosetta version: rosetta.binary.linux.release-171 r171 2018.09+release.333d996 333d99699777cd6a50d1c1736bacd689f8f1d1df https://www.rosettacommons.org 2018-02-27T09:57:00.705373
core.init: command: /home/shuhao/Downloads/rifdock/build/apps/rosetta/rifgen @input/rifgen.flag
core.init: 'RNG device' seed mode, using '/dev/urandom', seed=-1012113832 seed_offset=0 real_seed=-1012113832
core.init.random: RandomGenerator:init: Normal mode, seed=-1012113832 RG_type=mt19937
Rifdock thinks there are 8 threads.
rif_type: RotScore64

=================================================== preparing target ===================================================

basic.io.database: [ WARNING ] Unable to locate database file chemical/residue_type_sets/fa_standard
core.chemical.GlobalResidueTypeSet: For ResidueTypeSet fa_standard there is no exclude_pdb_component_list.txt file to list known PDB ids.
core.chemical.GlobalResidueTypeSet:     This will turn off PDB component loading for ResidueTypeSet fa_standard
core.chemical.GlobalResidueTypeSet:     Expected file: /home/me/rifdock/rifdock_rosetta/main/database/chemical/residue_type_sets/fa_standard/exclude_pdb_component_list.txt

ERROR: Unable to open file: /home/me/rifdock/rifdock_rosetta/main/database/chemical/residue_type_sets/fa_standard/residue_types.txt

ERROR:: Exit from: /home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/src/core/chemical/GlobalResidueTypeSet.cc line: 144
BACKTRACE:
/home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/cmake/build_cxx11_omp/libutility.so(utility::exit(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x2ea) [0x7ff474d4922a]
/home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/cmake/build_cxx11_omp/libcore.2.so(core::chemical::GlobalResidueTypeSet::init_restypes_from_database()+0xe48) [0x7ff47800f558]
/home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/cmake/build_cxx11_omp/libcore.2.so(core::chemical::GlobalResidueTypeSet::GlobalResidueTypeSet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1b6) [0x7ff47801d6a6]
/home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/cmake/build_cxx11_omp/libcore.2.so(core::chemical::ChemicalManager::create_residue_type_set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x21a) [0x7ff477febe6a]
/home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/cmake/build_cxx11_omp/libcore.2.so(boost::detail::function::function_obj_invoker0<boost::_bi::bind_t<std::shared_ptr<core::chemical::GlobalResidueTypeSet>, boost::_mfi::cmf1<std::shared_ptr<core::chemical::GlobalResidueTypeSet>, core::chemical::ChemicalManager, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list2<boost::_bi::value<core::chemical::ChemicalManager*>, boost::reference_wrapper<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> > >, std::shared_ptr<core::chemical::GlobalResidueTypeSet> >::invoke(boost::detail::function::function_buffer&)+0x3e) [0x7ff477ff2f1e]
/home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/cmake/build_cxx11_omp/libcore.2.so(core::chemical::ChemicalManager::residue_type_set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x2df) [0x7ff477ff006f]
/home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/cmake/build_cxx11_omp/libcore.2.so(core::chemical::ChemicalManager::residue_type_set(core::chemical::TypeSetMode)+0x39) [0x7ff477ff0819]
/home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/cmake/build_cxx11_omp/libcore.2.so(core::conformation::Conformation::residue_type_set_for_conf(core::chemical::TypeSetMode) const+0xca) [0x7ff477edce5a]
/home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/cmake/build_cxx11_omp/libcore.3.so(core::pose::Pose::residue_type_set_for_pose(core::chemical::TypeSetMode) const+0x21) [0x7ff475ea6061]
/home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/cmake/build_cxx11_omp/libcore.5.so(core::import_pose::pose_from_file(core::pose::Pose&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, core::import_pose::ImportPoseOptions const&, bool, core::import_pose::FileType)+0x9d) [0x7ff47526c25d]
/home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/cmake/build_cxx11_omp/libcore.5.so(core::import_pose::pose_from_file(core::pose::Pose&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, core::import_pose::FileType)+0x4d) [0x7ff47526c35d]
/home/shuhao/Downloads/rifdock/build/apps/rosetta/rifgen(main+0x7d4) [0x431114]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ff473ffc083]
/home/shuhao/Downloads/rifdock/build/apps/rosetta/rifgen(_start+0x2e) [0x43967e]
terminate called after throwing an instance of 'utility::UtilityExitException'
  what():

File: /home/shuhao/Downloads/rosetta_bin_linux_2018.09.60072_bundle/main/source/src/core/chemical/GlobalResidueTypeSet.cc:144
[ ERROR ] UtilityExitException
ERROR: Unable to open file: /home/me/rifdock/rifdock_rosetta/main/database/chemical/residue_type_sets/fa_standard/residue_types.txt

**Comment by zzhan88** [comment]
Hi, has your problem been solved? I got the same error as you
