### ISSUE TITLE
Missing files when compling rifdock and rifgen with hdf5 mode

### ISSUE THREAD

**Issue by Setsuna111** [rifdock/rifdock#153]
Hi @bcov77,

I compiled rifdock under Rosetta 3.9, gcc-6.3.0 successfully. Also, I'm trying to use RifGen with PyRIF. In this situation, the rifdock need to be compiled with hdf5 mode. 

However, when I set the related flag in CMakeList.txt (using `add_definitions("-DUSEHDF5")`), the compilation failed due to missing files named **DirectSegmentLookupMover.hh**, reporting error below:

In file included from /home/projects_dir/rifdock/apps/rosetta/riflib/util.cc:11:0:
/home/projects_dir/rifdock/apps/rosetta/./riflib/scaffold/util.hh:32:80: fatal error: protocols/indexed_structure_store/movers/DirectSegmentLookupMover.hh: No such file or directory
 #include <protocols/indexed_structure_store/movers/DirectSegmentLookupMover.hh>

I found the required files in `protocols/indexed_structure_store/movers/` were not included in Rosetta 3.9! The earliest version of Rosetta that included these files is 2018.44. Unfortunately, this Rosetta is not supported for RifDock.

I'd like to kindly ask you how to compile rifgen and rifdock in h5 mode rightly? Is there any problem that directly setting `add_definitions("-DUSEHDF5")`? 

Many thanks in advance.

Best, 
Fengji

**Comment by bcov77** [comment]
Congrats on being the first person to try to build that version! (Or at least the first person to contact me about it).

You're right that it's not possible from the information available or Rosetta 3.9. If you have access to the rosetta commons github, it's this branch: `bcov/fordas/structure_store2_grid_silent`

But, since you likely don't have access. I decided I'd just post the source here. Rosetta is moving to open source and they no longer even require a password to download the source. I doubt anyone will mind too much if I post a 5-year old version of the code.

https://files.ipd.uw.edu/pub/robust_de_novo_design_minibinders_2021/rosetta_versions/rosetta_source_for_rifdock_hdf5.tar.gz

**Comment by Setsuna111** [comment]
Thanks a lot for your quick reply! 

I have successfully built PyRIF and got the expected rif.h5 using the Rosetta files you sent to me. Thanks again for your nice work and really kind help!

What’s more, there are still another two small errors I met when compiling rifdock with hdf5 option. Maybe I should post the solutions below as a reference:

**Problem 1:**

The Rosetta file provided seems to be missing a file named `utility/version.hh`, reporting error:

```
/home/projects_dir/rosetta_source_for_rifdock_hdf5/main/source/src/protocols/peptide_deriver/PeptideDeriverMarkdownStreamOutputter.cc:26:30: fatal error: utility/version.hh: No such file or directory  
#include <utility/version.hh>
```

This can be solved by copying the same `utility/version.hh` from Rosetta 3.9, although there is a warning `“This file is utomatically generated by the build system.  DO NOT try modifying it by hand“` in this file, but it works.

**Problem 2:**

This problem is probably due to the installed hdf5 package, happening when the compilation process reaches almost 100%:

```
/usr/bin/ld: riflib/libriflib.so: undefined reference to H5::PredType::NATIVE_INT16
```

Other similar messages are omitted.

To solve this, I changed the `CMakeLists.txt` to link riflib to hdf5 libraries as followings:

**Change `CMakeLists.txt` in the root directory ("/home/projects_dir/rifdock/“):**

Add:

```
set(HDF5_INCLUDE_DIRS "/usr/include/hdf5/serial/")  # replace with your hdf5 include path
set(HDF5_LIBRARIES "/usr/lib/x86_64-linux-gnu/libhdf5_cpp.so" "/usr/lib/x86_64-linux-gnu/libhdf5_hl_cpp.so")  # replace with your hdf5 lib path
```

Note that the hdf5 lib path created by anaconda is not reliable.

**Change `CMakeLists.txt` in the riflib directory ("/home/projects_dir/rifdock/apps/rosetta/riflib/“)**

Add:

```
link_directories( ${HDF5_LIBRARIES} )
target_link_libraries ( riflib ${HDF5_LIBRARIES} )
```

Perhaps the comments in this `CmakeLists.txt` should be removed in hdf5 mode :)

Hope these solutions will help with your development of the Rosetta software.

**Comment by Setsuna111** [comment]
Hi @bcov77  ,
I'm currently working on utilizing RIFGen with PyRIF, and I’ve successfully compiled rifdock under Rosetta 3.9, gcc-6.3.0 in hdf5 mode under your guide.

However, when attempting to load the hdf5 file generated by RIFGen, errors occurred as following:
```
Traceback (most recent call last):
  File "/home/projects_dir/rifab/main.py", line 23, in <module>
    RIF = RotamerInteractionField(
  File "/home/anaconda3/envs/rif/lib/python3.8/site-packages/pyRIF/pyRIF.py", line 71, in __init__
    self.L_AA_RIF = self.load_RIF_Table(**L_AA_RIF_kwargs)
  File "/home/anaconda3/envs/rif/lib/python3.8/site-packages/pyRIF/pyRIF.py", line 130, in load_RIF_Table
    rif_dict[f['xbin_key'][:]] = f['offsets'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/anaconda3/envs/rif/lib/python3.8/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 241, in h5py.h5o.open
KeyError: "Unable to synchronously open object (object 'offsets' doesn't exist)“
```
It appears that the index keys ‘offset’ and ‘xbin_key’ are missing from the generated hdf5 file. After reviewing the source of the hdf5 generation process in RIFGen `rifdock/apps/rosetta/riflib/RifFactory.cc`, line 277, I noticed that the generated hdf5 file only includes the following four elements: 

`<KeysViewHDF5 ['bin_center', 'cart_ori_bound', 'irots', 'scores']>`

I want to inquire if extra settings are needed to save this information? Or if there is a version mismatch between PyRIF and RIFGen?

Many thanks in advance.

Best,
Fengji

**Comment by bcov77** [comment]
Wow! I had no idea that python library existed. Weirdly also I wrote a lot of the code for it...

Anyways, I think you forgot to run this (which the instructions over there tell you to run):
`python tools/convert_rif_h5.py`

**Comment by Setsuna111** [comment]
Really good advice! Actually I forgot to run it...

Thanks for your help again!
